### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by ellisgl** [cdev-tux/q3lite#1]
Just getting "Awaiting Challenge..." when trying to the server.

    root@raspberrypi:/usr/local/games/quake3# ./q3ded.armv7l
    Q3lite 1.0.0 linux-armv7l Nov 28 2017
    ----- FS_Startup -----
    We are looking in the current search path:
    /root/.q3a/baseq3
    ./baseq3
    ./baseq3/pak8.pk3 (9 files)
    ./baseq3/pak7.pk3 (4 files)
    ./baseq3/pak6.pk3 (64 files)
    ./baseq3/pak5.pk3 (7 files)
    ./baseq3/pak4.pk3 (272 files)
    ./baseq3/pak3.pk3 (4 files)
    ./baseq3/pak2.pk3 (148 files)
    ./baseq3/pak1.pk3 (26 files)
    ./baseq3/pak0.pk3 (3539 files)

    ----------------------
    4073 files in pk3 files
    execing default.cfg
    execing q3config_server.cfg
    execing autoexec.cfg
    Hunk_Clear: reset the hunk ok
    --- Common Initialization Complete ---
    logfile opened on Wed Nov 29 03:59:45 2017

    IP: 127.0.0.1
    IP: 192.168.15.251
    IP6: ::1
    IP6: 2600:1700:xxxx
    IP6: 2600:1700:xxxx
    IP6: fe80::xxxx%eth0
    Opening IP socket: 0.0.0.0:27960
    ]

netstat shows the port, but not in listening mode.

    root@raspberrypi:/home/pi# netstat -tulpn
    Active Internet connections (only servers)
    Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
    tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      506/sshd
    tcp6       0      0 :::22                   :::*                    LISTEN      506/sshd
    udp        0      0 0.0.0.0:42722           0.0.0.0:*                           338/avahi-daemon: r
    udp        0      0 0.0.0.0:5353            0.0.0.0:*                           338/avahi-daemon: r
    udp        0      0 0.0.0.0:27960           0.0.0.0:*                           9062/.
    udp        0      0 0.0.0.0:68              0.0.0.0:*                           502/dhcpcd
    udp6       0      0 :::51429                :::*                                338/avahi-daemon: r
    udp6       0      0 :::5353                 :::*                                338/avahi-daemon: r
    udp6       0      0 :::546                  :::*                                502/dhcpcd

autoexec.cfg

    set vm_game 1           //
    set vm_cgame 1          //
    set vm_ui 1             //
    set dedicated 1         // Dedicated server but not announced
    set com_hunkmegs 512    // How much RAM for your server
    set net_port 27960      // The network port

    // general server info
    seta sv_hostname "House of Ellis" // name that appears in server list
    seta g_motd "Quake on Pi"         // message that appears when connecting
    seta sv_maxclients 32             // max number of clients than can connect
    seta sv_pure 1                    // pure server, no altered pak files
    seta g_quadfactor 4               // quad damage strength (3 is normal)
    seta g_friendlyFire 1             // friendly fire motherfucker

    // capture the flag
    //seta g_gametype 4               // 0:FFA, 1:Tourney, 2:FFA, 3:TD, 4:CTF
    //seta g_teamAutoJoin 0           // 0:goes into spectator mode, 1:auto joins a team
    //seta g_teamForceBalance 0       // 0:free selection, 1:forces player on weak team
    //seta timelimit 30               // Time limit in minutes
    //seta capturelimit 8             // Capture limit for CTF
    //seta fraglimit 0                // Frag limit

    // team deathmatch
    //seta g_gametype 3             // 0:FFA, 1:Tourney, 2:FFA, 3:TD, 4:CTF
    //seta g_teamAutoJoin 0         // 0:goes into spectator mode, 1:auto joins a team
    //seta g_teamForceBalance 1     // 0:free selection, 1:forces player on weak team
    //seta timelimit 15             // Time limit in minutes
    //seta fraglimit 25             // Frag limit

    // free for all
    seta g_gametype 0             // 0:FFA, 1:Tourney, 2:FFA, 3:TD, 4:CTF
    seta timelimit 10             // Time limit in minutes
    seta fraglimit 30             // Frag limit

    seta g_weaponrespawn 2          // weapon respawn in seconds
    seta g_inactivity 120           // kick players after being inactive for x seconds
    seta g_forcerespawn 0           // player has to press primary button to respawn
    seta g_log server.log           // log name
    seta logfile 3                  // probably some kind of log verbosity?
    seta rconpassword "password"      // sets RCON password for remote console

    seta rate "12400"               // not sure
    seta snaps "40"                 // what this
    seta cl_maxpackets "40"         // stuff is
    seta cl_packetdup "1"           // all about

    set d1 "map q3dm1 ; set nextmap vstr d2"
    set d2 "map q3dm2 ; set nextmap vstr d3"
    set d3 "map q3dm3 ; set nextmap vstr d1"
    vstr d1

**Comment by cdev-tux** [comment]
There's a setting in the autoexec.cfg file that's installed with Q3lite that you may need.  Try adding this line to your autoexec.cfg:  
seta net_mcast6addr "ff04::696f:7175:616b:6533"		// Set multicast address to use for scanning for ipv6 servers on the local network.

**Comment by ellisgl** [comment]
I'm trying to connect to it from my PC using IOQuake via the IPv4 address.

**Comment by cdev-tux** [comment]
Check the server.cfg file to see if this setting exists:  
seta net_enabled "3"  

Also try adding the net_mcast6addr line from above to your server.cfg file.

**Comment by ellisgl** [comment]
I think I might have found the issue, I was editing under /usr/local/games/quake3/baseq3 insted of ~/.q3a/baseq3

will report back...

**Comment by ellisgl** [comment]
So removed it, all .q3a folders, re-installed (this time leaving the client in too), and only ran as sudo from pi user and all is looking good now. Basically I didn't RTFM very well.

**Comment by cdev-tux** [comment]
Glad to hear it's working.  Have fun with it.
