### ISSUE TITLE
Servers

### ISSUE THREAD

**Issue by angrynerd** [cdev-tux/q3lite#12]
I was wondering is q3lite clients and servers compatible with regular q3 clients?

**Comment by cdev-tux** [comment]
Hello,

Q3lite is built on ioquake3, so it’s compatible with original Q3 clients and servers.  Q3lite clients can join Q3 servers and original Q3 clients can join Q3lite servers.

**Comment by cdev-tux** [comment]
Let me know if you have any other questions.  Thanks.
