### ISSUE TITLE
ut

### ISSUE THREAD

**Issue by symbios24** [cdev-tux/q3lite#13]
Hello there im trying to use your engine on a raspberry pi3 to play the urban terror

Are there specific instructions/commands to run a mod/standalone game with q3lite?

i tried to launch the game from latest raspbian lite with this command ./quake3.armv7l  +set com_hunkMegs 320 +set  fs_game q3ut4 (where the q3ut4 folder is the urban terror v4 game)
it worked i loaded the first map but i had artifacts on screen and the mouse was not working correct the whole game was not responding.
are there any extra commands to add to the /quake3.armv7l to make it work correct>?
i compiled the game engine following the normal instructions here
Thanks

**Comment by cdev-tux** [comment]
Hello,

I don’t know much about Urban Terror but I’ll try to help if I can.  Check with the Urban Terror project and verify that the mod runs on the latest version of ioquake3.  If not then the mouse and keyboard probably won’t work correctly.  I saw on the UrT forums that the game uses around 400MB of ram, so you might try to bump the com_hunkmegs setting up a bit.  Also try to set the video memory split slightly higher than 128MB.  At that point you’ll probably need to run the game on Raspbian Lite to have enough available RAM.  Close as many unneeded background programs and processes as possible.  Let me know if that helps.  Can you open the console and issue the /condump command?  If so, post the output here and I’ll take a look at it.

Thanks

**Comment by symbios24** [comment]
i did that i tried many things always the same result,maybe you need to test this also your self as you are more experienced,it will be great addition to the engine to support fully urban terror as it is a very popular game.

**Comment by cdev-tux** [comment]
According to an article on Phoronix, Urban Terror moved away from Open-Source around 2010.  The code that you’re running was probably released around 2008.  I don’t have the programming expertise to update that codebase, and there’s no way that I could do all of that by myself even if I knew how.  I’m afraid I can’t help out with this, sorry.

**Comment by symbios24** [comment]
ok no problem thanks

**Comment by symbios24** [comment]
hi again is it possible to run q3lite without the need of the original pak0.pk3 just to use the demo pak0.pk3 ? right now it asks for the original file if i put the demo file is there a setting to overide this with the demo of quake3?

thanks

**Comment by cdev-tux** [comment]
In the [Compiling and Installation Guide](https://github.com/cdev-tux/q3lite/wiki/Compiling-Install-Guide) there’s a link to the ioquake3 forums that has information on getting that to work.  Read step 7 under the Installation section and you’ll see the link.  I haven't tried it so I can't confirm that it works.
