### ISSUE TITLE
smoking guns game

### ISSUE THREAD

**Issue by retro24** [cdev-tux/q3lite#15]
Hello great engine

im trying to run smokinguns game that uses the same engine in a Raspberry pi 3
while im succeded into trying the quake3 rally game
in smoking guns it stucks in the Loading now screen although it loads ok plays videos etc
but when i go to the single player and select any level and press load it stucks in the loading now screen if a press any buttons it goes back to main menu

i have the game running with ./quake3.armv7l +set fs_game smokinguns

the gpu shared mem is 192mb

any suggenstion?

**Comment by cdev-tux** [comment]
Unfortunately I don’t have any experience with Smokin' Guns so I’m afraid I can’t be of much help. You could contact the authors through their Discord channel to see if they have any suggestions. The link is on their webpage.

Thanks

**Comment by retro24** [comment]
i did nobody answers thanks but still what can i say to them ? that is not working with q3lite ?
