### ISSUE TITLE
Raspberry pi 4 support

### ISSUE THREAD

**Issue by symbios24** [cdev-tux/q3lite#17]
Hello will you add support for the Raspberry pi 4 ??
Thanks

**Comment by jacobo-mc** [comment]
he said he is working on it

**Comment by confuzled** [comment]
its on rpi 4

**Comment by randomMesh** [comment]
Is this project still active (last commit Apr 20, 2020)?
I'd love to see it running on RPI 4.

**Comment by cdev-tux** [comment]
I won't be working on this any time soon. You can run ioquake3 on the Pi 4.

**Comment by randomMesh** [comment]
Thanks for your fast respronse and your clarification.
