### ISSUE TITLE
q3a-server guide

### ISSUE THREAD

**Issue by roguephysicist** [cdev-tux/q3lite#2]
Hi,

Great work guys. I love seeing these types of projects for the RasPi.

I previously published a quick guide for setting up a Q3A server. It is well suited for the RasPi and other low-power systems. Perhaps you would be interested in adding a [link to the repo](https://github.com/roguephysicist/q3a-server) or using the config files for your own project?

Cheers!

**Comment by cdev-tux** [comment]
Thanks for the kind words, much appreciated.

**Comment by ellisgl** [comment]
Sorry to re-open - but you didn't answer the question about linking his repo in the readme.

**Comment by cdev-tux** [comment]
My bad, I’m new at this.  I added a link to your (roguephysicist) repo on the main wiki page under the [Resources/Links section](https://github.com/cdev-tux/q3lite/wiki#resourceslinks).  I have config files currently in the repository, but I’ll look through the files you have.  That’s a great reference.

**Comment by roguephysicist** [comment]
Awesome, thanks!
