### ISSUE TITLE
Q3lite compatible with Pi Zero 2 W running Raspberry Pi OS Buster

### ISSUE THREAD

**Issue by Srandista** [cdev-tux/q3lite#21]
Hi @cdev-tux.
I just want to confirm, that Q3lite is still compatible with Pi Zero 2 W running Raspberry Pi OS based on Debian Buster.

Since Zero 2 W is really just a under-clocked Pi 3 in Zero size and Buster based OS still works on it, I gave it a go, and with small addition to install script, it compiled and run without any issue.

"^Revision\s*:\s*[ 123][0-9a-f][0-9a-f][0-9a-f]12[0-9a-f]$"

I'm getting 89 fps in FullHD with included timedemo four.

**Comment by cdev-tux** [comment]
Excellent! Thanks for sharing this.

**Comment by symbios24** [comment]
I managed to run urban terror on pi3 with over 50 fps
