### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Packjackisback** [cdev-tux/q3lite#22]
Getting error at the compile step, it might be an error on my end, but I’m getting this:
![image](https://user-images.githubusercontent.com/83289186/230652873-2ee2198c-5b43-4984-8ed0-924f9eb41cfa.jpg)

**Comment by Srandista** [comment]
Are you trying this on Buster? It's not compatible with Bullseye, or with RPi4. Can you please provide more info?

What RPi are you using? For version of Raspbian, please use following command: "lsb_release -a" and paste the output here.

**Comment by Packjackisback** [comment]
Oh. I'm on bullseye. I apologize for the inconvenience. Is Bullseye support planned?
