### ISSUE TITLE
Unable to determine platform type from /proc/cpuinfo 

### ISSUE THREAD

**Issue by cdkw2** [cdev-tux/q3lite#23]
I just ran ``` ./make-raspberrypi.sh ``` but it gave me this

![image](https://github.com/cdev-tux/q3lite/assets/67598073/16493600-a1e3-45c9-bbac-84fff1c8756e)

**Comment by cdkw2** [comment]
I am using a 
```
OS: Debian GNU/Linux 11 (bullseye)
OS architecture: 64-bit
Kernel: aarch64 6.1.21-v8+
Device model: Raspberry Pi 4 Model B Rev 1.2 
Cpu name: Cortex-A72
Ram size: 3.79 GB
Raspberry Pi OS image version: 2023-05-03
Language: en_US.UTF-8
```

**Comment by cdkw2** [comment]
Is it because I am using a raspberry pi 4?

**Comment by cdev-tux** [comment]
Hello,

This is an old project that was written for the Pi 3 and older units. Due to changes with the OS it also requires Raspberry Pi OS (Legacy) buster.

Thanks

**Comment by cdkw2** [comment]
oh ok!
