### ISSUE TITLE
not an issue.. but a thankyou!

### ISSUE THREAD

**Issue by wmjb** [cdev-tux/q3lite#24]
managed to get this compiling on ubuntu 16.04 with the 3.4 downstream kernel on the Microsoft Surface RT 1 and 2 (arm32). runs great and uses the nvidia gles driver for full gpu acceleration. 

thank you for making this port! 

https://www.youtube.com/watch?v=mMpF92WXV4I

**Comment by cdev-tux** [comment]
Thank you for the kind words!
