### ISSUE TITLE
Can't not type words at 'Talk' funsion

### ISSUE THREAD

**Issue by kenneth-Q** [cdev-tux/q3lite#5]
Hello.
Thanks for your project. I am using raspberry pi 3 for this game and so nice!

But however, I could not type something at the funsion --> talk, when I tick 'T' at my keyboard, and I see a 'say: ' on the screen. But I cannot talk everything, 
Please fix.
Thanks again.

**Comment by cdev-tux** [comment]
Hello,
I pushed a fix that will hopefully address the issue.  Please compile the latest "dev" branch and let me know if it fixes your issue.  Thank you for your help.

**Comment by cdev-tux** [comment]
Look at the troubleshooting section of the [Compiling and Installation Guide](https://github.com/cdev-tux/q3lite/wiki/Compiling-Install-Guide) and see if any of those suggestions help.  Test on a spare SD card with a fresh install of Raspbian Stretch.  You may have some installed packages or system settings that are preventing it from working correctly.  Please let me know if it works on a fresh install.  Thank you.

**Comment by cdev-tux** [comment]
Have you tried this on a fresh install of Stretch?  What does it return when you type "sdl2-config --version"?

**Comment by cdev-tux** [comment]
It's working here on a fresh install of Stretch, so I don't have any way to reproduce this.  Please reopen if you want to troubleshoot the issue again.
